language: python
python:
  - '2.7'
install:
  - pip install -U pip setuptools
  - pip install -Ur requirements/frozen.txt
script: py.test cfme/utils/tests -v --dummy-appliance
after_success:
  - coveralls